### PR TITLE
Add LFRic testing requirement traclog comments

### PR DESCRIPTION
**Pull request by james-bruten-mo**
Once UM  #7311 is on, an update to instructions for whether LFRic testing must be completed.

### CODE REVIEW

**Review by r-sharp — COMMENTED** [review]
Well those changes look good to me, but I'm concerned if I approve the pull request, it will get automatically merged. So I'm just going to comment for now.

**Comment by jennyhickson** [comment]
This repo isn't set up with automatic merging at the moment, so approving the review simply reveals the "merge to main" button but doesn't do anything by itself.

**Comment by james-bruten-mo** [comment]
Anders has committed UM:#7311 now so I this is no longer blocked. Cheers

**Review by andrewcoughtrie — APPROVED** [review]
Since @r-sharp already agrees that this is all good and @james-bruten-mo has commented that the blocking ticket has been completed. The change looks good to me too so I'll merge it in.

**Pull request merged**
